package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/devXpro/paseo-whisper/internal/terms"
)

// termsCommand implements `paseo-whisper terms <scan|show>`.
func termsCommand(sub string, rest []string, f flags) error {
	switch sub {
	case "", "scan":
		return termsScan(f)
	case "show":
		return termsShow(f)
	default:
		return fmt.Errorf("unknown terms command %q (try: scan, show)", sub)
	}
}

func termsScan(f flags) error {
	roots := terms.DefaultRoots()
	if len(roots) == 0 {
		return fmt.Errorf("no Claude transcripts found; nothing to learn from")
	}

	fmt.Println("\n  scanning your own chat history for domain vocabulary")
	for _, r := range roots {
		fmt.Printf("    %s\n", r)
	}

	found, messages, err := terms.Scan{
		Roots:    roots,
		MinCount: f.minCount,
		Limit:    f.limit,
	}.Run()
	if err != nil {
		return err
	}
	if len(found) == 0 {
		return fmt.Errorf("no terms passed the threshold; try --min-count 3")
	}

	fmt.Printf("\n  %d messages read, %d terms kept\n\n", messages, len(found))
	for i, t := range found {
		fmt.Printf("  %-22s %4d", t.Word, t.Count)
		if i%2 == 1 {
			fmt.Println()
		}
	}
	if len(found)%2 == 1 {
		fmt.Println()
	}

	body := renderTermsFile(found)
	if !f.write {
		fmt.Printf("\n  %d characters, roughly %d tokens (Whisper accepts 224)\n",
			len(body), estimateTokens(body))
		fmt.Println("\n  write it with:  paseo-whisper terms scan --write")
		fmt.Println()
		return nil
	}

	target := f.promptFile
	if target == "" {
		target = "terms.txt"
	}
	if err := os.WriteFile(target, []byte(body), 0o644); err != nil {
		return err
	}
	fmt.Printf("\n  wrote %s (%d characters, ~%d tokens)\n", target, len(body), estimateTokens(body))
	fmt.Println("  restart the server to use it:  make run")
	fmt.Println()
	return nil
}

func termsShow(f flags) error {
	target := f.promptFile
	if target == "" {
		target = "terms.txt"
	}
	data, err := os.ReadFile(target)
	if err != nil {
		return err
	}
	fmt.Printf("\n%s\n  %d characters, roughly %d tokens (Whisper accepts 224)\n\n",
		data, len(data), estimateTokens(string(data)))
	return nil
}

// renderTermsFile lays the vocabulary out newest-relevant last: Whisper weighs
// the tail of a prompt more heavily, so the most frequent terms go at the end.
func renderTermsFile(found []terms.Term) string {
	var b strings.Builder
	b.WriteString("# Generated by: paseo-whisper terms scan --write\n")
	b.WriteString("# Vocabulary mined from your own chat history.\n")
	b.WriteString("# Whisper weighs the end of a prompt more heavily, so the most\n")
	b.WriteString("# frequent terms are listed last. Edit freely; keep it under ~200 tokens.\n\n")

	words := make([]string, 0, len(found))
	for i := len(found) - 1; i >= 0; i-- {
		words = append(words, found[i].Word)
	}

	const perLine = 8
	for i := 0; i < len(words); i += perLine {
		end := i + perLine
		if end > len(words) {
			end = len(words)
		}
		b.WriteString(strings.Join(words[i:end], ", "))
		b.WriteString("\n")
	}
	return b.String()
}

// estimateTokens approximates Whisper's tokenisation: Latin text packs about
// four characters per token, Cyrillic barely two.
func estimateTokens(s string) int {
	latin, cyrillic := 0, 0
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			latin++
		case r >= 'а' && r <= 'я', r >= 'А' && r <= 'Я', r == 'ё', r == 'Ё':
			cyrillic++
		}
	}
	return latin/4 + cyrillic/2
}
